language: python
python:
- '3.5'
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
env:
  matrix:
  - DJANGO=2.0.1 DB=postgres
  global:
  - secure: nW7/wOydtPZxz7vSzenrKWiRA8e9d79xnMLTbGpXVC6LH/NmkfW1zr1E5qKeFdtVgI5ePmUPwxUCRjTVF5fhUtFKoYRppDJttwZtMhrpMQ2ejElmBfCUGHXfiDC2sSOf43GxzR/C8o0dsaiHrcpUzB+qLOozcUnjUMaO9EF49/AkmB/CVgfbwRoDvsWJGc69MaRRbd3AnfdgTYbx3ycOKYdOvmFebbF6f4Y5o/89CFVrv7yplWEx7HaTrVTfgXAi9OTywgpmrLMHYGIYZSf9w4NRS6vnXp74u6toXy763413Fn/Eyeuuk830Fy+SCmh/Lc8PdMVAJLNh0UHcaMx9yP5zfl7xT7cx2q1aBEKOhUdXDG77+1BLb4E8/rHwmbfOc8o/PJdPceRSOY62obWg111SY9wG8O2eASTECvzhoIHhgi/Vg8/NuRdu01lORavYijZt2MHL3O/R9DktUsZ6lvBcK9mgK1VN+h/Xy0b5oMqjIfGWtceMLyz3PYg6LDTlSXQcveVRIjQhcy+xhWMMLHFmDs/I2Hc1HvPu8GO7PVYk7GaRMBTz0fOqwJCB6Id7TVLc3vFVKMmFQL4zxwruSC9rd0C4spogHvZ/XlOKhcDcZqhy7E6jolS0t0VNonpXyFmuYaN7gF9A1JcCxgFOXuM0gZ5qihQT8iCwRPCizds=
  - secure: RP8OCf7le/C+MwYgU0RjFTiQbG2djoMVjxAldRi6w/GshfYQonfvhH09rW72/7c+BLwQOiebUfdzEjcilm6h8PiTC/6PAk9h8qTt1X7dT1t0zuUal5Cu9jiWxqwOKAu9Ql7yrOVkRv36ZJfjW7U9jpuZdYWxTiRzPKkJwmSMKNyThY7dJaqzGFcxtWiOJ/vrROrSWUxMlv9j7AN01q+594MDLc2PDHIVE3Jz9A5yYIevZaLvSNnYMI37gov9QDGDn6tHKfRO+TvJMdzkhSH67S6C02at19Q+6CdnZFwP0gS0HGf6LJdb8jQiazWSa3hPR/gl1+GkXzeRR5B7AzaXp7W3wkVcoumhMhFsY0srK66SgUCjEAMj6x/Zud9zCMWrIGmxM2aQ2hFrfKa44QGhasUqZc4xGMFEdRYwjODzbrx/IzM9n7GqcpuImoLK5OazMg/PxUFPG9b0tPEQyNb6dH7xHQteRQBeCeL/Hnptqolou4hXDAmQ+k2QZ9cSgGfU7fkYk8yxdP86B+kr7695u2Na7F0UgY0s5qgeKjThzmvOw8aNNRaCKvAY1zZyRhZ9m9T9h1Hran5u1PDq14jpgceIcKKXlgR82rFq7Js74KRNHeOoK/IbyqvIaiYG1LkQpmboY+Lffn7NH2ZmHpYFBYFGUqFLuywCG1ZIVQR/FkU=
  - secure: Eyz5DSRHs8E+UGClSaeLLyXbPim57KnKFngdTu5U7nnmHgYmvoS5QMVPPMbZdhYuLUnG9sygbXLj4k7gR+E3tUK6tdh+rrHnH9N/D1jK3y1jNVYc0iXThW77Fm3abjW6BKX4sSUJkMUAajuQsov6D5cVgy2EX6FVYgDLPiTl1Fr2jxIMAoDVeM71eAb2GAraTLuEdDydMLOyz8pkZjQzwCeqWjM78XUCXNkiR8ksa60wd92y8I9POA6cDDlZ9hlqFzX3HpIgM8lN8pLzKGUtJE3/DbSQiHGxuOWgfWWGBjNCK5TYWSNZgoGCc5SkUvfW1Op1HO7Nt+iE/7VvHDrQIe1qSh4OGnug/jg6fQrDK9ZupuhMfOih4zN5qaoVtYErdGS8ahCTVGFVWYmGPThz2+EzEw4ojlPlpPSvyKgSjLfnwb4X8dcH4KtgBZXl/Q0q/4ZFTQHj/gZg4FvtfS6oKm++fwyU33iQgxOxK2qphCe6E3MkKavlUY+FfL0eXI2YxBbYCbpU2C5SAxUUiZNqIMqGUJNL79iXNuP7e6+DXFs7aScKj5zOHaLaRQuHahdfTIxh+fmfnDktKOAKZTChU5J7Cn957CtifLIN9bCZ2cGuj5ATaKJiuK9RwhkSz3FXJNjSNN2TA93aw8YJjbFlDtHJ4l5WvhHuOvLeCpdRlZk=
  - secure: VjFyPdbUWv2pk92meSjSlM+SVSmjmPPBc1p6Ptf5WbqxkigdiuY5eQLc9Yl59Ds9byuCb23K91x3lWc6cd3bQGtwPxnHBuc8+qoEOWY1BOKlrgyC1ntunbykJThtSZR7caqfASP67loCS5ObS1uKFrEdvD/uIcGHW9euDAROfXQHd87CBNYGY4fEehkMwgE4qvduwM6yBGc/K4v2FJgY+wyz7RK6J5/5D8KoMnvwaTJPvr4jAcKenQ7bV//+hM0oBO9crwoJA8RakVNX3wFPOdPq0yCz4AmYCNxlyTHkv0P2MzMaJaXqUkf9bJAkZeA3n7dtJ97dJbIFwEB0KZgZrQ47/JAXBRPLCr21p1SowoG8+cOQPNa9KFuReA/KLg/5rdwqqykaVv8mGk2AR5fwRiAoUYbmpouWPy8cODR2u2frgHF3Mk4E2wgLOQ/j4QiD61uex49FRHMC48G578JbZYsY3KUJV43H0jRxinz2Ovs4a+Da5WThXitpc7+j6lEp9nPTzzrNixnSythsDEZzucO5VEAv/RrHiEOsDaI0vQW24uioJDDlRqDXH6mBAjnOKaWhzk4fawXqT5RuSknt5P0N2NP4lUgA7wgKu7mNeWIb88WyZ8DozpQBxp9PNMirBHy5IGqJNpPerx80dNT0MFLHHytJtXLOO9ffcJ+moFc=
  - secure: nsFoPt433dEvTyNZgEMd33ph9WcdYs6MvS/wJPN6y4ADE8ojqeiqljTFAPKHgiJaAZBsHvQv5RmZLk+C+ulFg7QLVVqZzyiU5NQK6aCSndhvGqOje9J0zgaxLIkIbMiw9oBbieXbS1pp2KTh/39RvjnZt3ju3Uj1S7eQOfOqXCamlwoyTHpw6gIRoccmydA6p5EpLJfRncR9w90qI4CCs++XUSc2eH1NLjs4U4qj4Gh1TFy1v7pa/ervlq12GUMIgnok+m9C8+PvdJEB6Rl1Hys6Run5LxCDD0OvXAKPuDomD2DEUbjkvr4299NZvmQqPghq19xgun8G/UOQkIuQC5l8qvrJMR/dMuIuMYuPvNP4+J+dEej2PxJVyF3+D7S+ce0I257SaQm4zxa6mn1pl5t0KiW7mdApFVVDIOjwBZ1WPi+9s0rJ7odr9Ei71P7vsPjdsA6li7sSM4bnzZ/tlRiAeM4kCf3Ysg8DMFK+eABW/BzgYekQ2hznzjX4aNAwf8UkOl5BuIhYPz8Ka726VSZXputr6BDkxiRCUXbxIG0Hc43jWTR/sO1uFGOtKB5/UptlhXsihUvyxqhVT2/t629KxgASgEv/wefPSmxcgXZ3ItYFJS81T0G67J1sOrEzCWwAsIE85gQTRawVoqLK0LMW2QL+qiWUTR03EGgLlMs=
branches:
  only:
  - development
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database espolguide_db;' -U postgres
- sudo -u postgres psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"
  espolguide_db
script: 
- python manage.py collectstatic 
- yes
- python manage.py test

after_success: 
- coverage report
