language: python

python:
  - "3.5"

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  - DJANGO=2.0.1 DB=postgres

# Whitelisting example
branches:
  only:
    - development

# command to install dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database espolguide_db;' -U postgres
  - sudo -u postgres psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;" espolguide_db

script:
  #coverage run --source=espolguide_app manage.py test
  python manage.py collectstatic
  python manage.py test

after_success:
  #coveralls
   coverage report
