#!/bin/bash

sudo apt-get update
sudo apt-get install python3-pip python-dev libpq-dev
sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#install postgres and postgis. Replace gisdata with your database name
sudo apt-get update
sudo apt-get install postgresql-9.5 postgresql-contrib-9.5
sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt install postgis postgresql-9.5-postgis-2.3
sudo -u postgres psql -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;" gisdata
#install jenkins
wget -q -O — https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c ‘echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list’
sudo apt-get update
sudo apt-get install jenkins
#follow db settings from 
#http://www.gis-blog.com/how-to-install-postgis-2-3-on-ubuntu-16-04-lts/
#https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-16-04
