# Generated by Django 2.0.1 on 2019-08-05 00:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity_name', models.CharField(max_length=80, verbose_name='zone')),
                ('code_gtsi', models.CharField(max_length=60, verbose_name='code')),
                ('code_infra', models.CharField(blank=True, max_length=60, null=True, verbose_name='code_infrastructure')),
                ('name_espol', models.CharField(max_length=80, verbose_name='name')),
                ('building_type', models.CharField(max_length=60, verbose_name='type')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='description')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('alternative_names', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Building',
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_create', models.DateTimeField(auto_now_add=True)),
                ('id_buildings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Buildings')),
            ],
            options={
                'verbose_name': 'Favorite',
            },
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_espol', models.CharField(max_length=250, verbose_name='detail')),
                ('salon_type', models.CharField(blank=True, max_length=60, null=True)),
                ('tag', models.CharField(default=None, max_length=60)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Buildings')),
            ],
            options={
                'verbose_name': 'Spaces (classrooms,laboratories,offices,...)',
            },
        ),
        migrations.CreateModel(
            name='Unities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Zone',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default=None, max_length=64)),
                ('token', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.AddField(
            model_name='favorites',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Users'),
        ),
    ]
