# Generated by Django 2.0.1 on 2018-07-25 20:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_infra', models.CharField(max_length=60)),
                ('code_gtsi', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=80)),
                ('name_infra', models.CharField(max_length=80)),
                ('building_type', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='type')),
                ('unity_name', models.CharField(max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('photo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_create', models.DateTimeField(auto_now_add=True)),
                ('id_buildings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('salon_type', models.CharField(max_length=60)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Unities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default=None, max_length=64)),
                ('token', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='id_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espolguide_app.Users'),
        ),
    ]
