# Generated by Django 2.0.1 on 2018-06-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espolguide_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
