# Generated by Django 2.0.1 on 2018-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espolguide_app', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tipo',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
