# Generated by Django 2.0.1 on 2018-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espolguide_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
